#!/usr/bin/env bash

set -e
cd "$(dirname "$0")/.."

install_zsh() {
  echo "Installing zsh…"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

install_brew() {
  echo "Installing brew…"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

  if [ "$(uname -s)" = "Linux" ]; then
    echo "Tapping https://github.com/athrunsun/linuxbinary"
    # Redirect stderr https://unix.stackexchange.com/a/119650/209107
    brew tap athrunsun/linuxbinary > /dev/null
  # elif [ "$(uname -s)" = "Darwin" ]; then
  fi
}

install_nvm() {
  echo "Installing nvm…"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
}

install_deno() {
  echo "Installing deno…"
  curl -fsSL https://deno.land/x/install/install.sh | sh
}

HOMESICK=$HOME/.homesick/repos/homeshick
install_homesick() {
  echo "Installing homesick…"
  git clone git://github.com/andsens/homeshick.git $HOMESICK
  source "$HOMESICK/homeshick.sh"
}

# Install tools, if uninstalled
bash -c "[ -d $HOME/.oh-my-zsh ]" &> /dev/null || install_zsh
brew --version &> /dev/null || install_brew
bash -c "[ -d $HOME/.nvm ]" &> /dev/null || install_nvm
deno --version &> /dev/null || install_deno
bash -c "[ -d $HOMESICK ]" &> /dev/null || install_homesick
